server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaee?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver